version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongo
  redis:
    image: redis
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    ports:
      - "27017:27017"